services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/web-scraping-app

  frontend:
    build: ./frontend
    ports:
      - '8080:80'

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-data:
